# Generated by Django 3.2.6 on 2021-11-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='13 Character <a href="https:                            //www.isbn-international.org/content/what-isbn                            ">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
