# Worker dockerfile: it should launch the worker process connecting to the masters

# Parent image
FROM ubuntu

# Add files to the container
ADD worker.sh worker.sh

# Launch the worker process
CMD ["./worker.sh"]


