apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30077 # Expose the cluster to port 30077