# Generated by Django 3.2.6 on 2021-12-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
