# Generated by Django 3.2.6 on 2021-12-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
